/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and is included here so typecheck works
// before the first local dev-server run.
